#!/usr/bin/env bash
SESSION_NAME="Dashboard"

tmux has-session -t "$SESSION_NAME" 2>/dev/null
if [ $? != 0 ]; then
  tmux new-session -d -s "$SESSION_NAME" -n "Workspace"
  tmux split-window -h -p 80
  tmux split-window -h -p 35
  tmux select-pane -t 1
  tmux split-window -v -p 50
  tmux select-pane -t 3
  tmux split-window -v -p 30

  tmux send-keys -t 0 "yazi" C-m
  tmux send-keys -t 1 "claude-pro" C-m
  tmux send-keys -t 2 "gemini-pro" C-m
  tmux send-keys -t 3 "glow -p ~/.tmux-cheatsheet.md" C-m
  tmux select-pane -t 4
fi

tmux attach-session -t "$SESSION_NAME"
