#!/usr/bin/env bash
session=$(tmux list-sessions -F "#{session_name}" 2>/dev/null | fzf --reverse --header="Select Session" --prompt="Switch> ")
if [[ -n "$session" ]]; then
    tmux switch-client -t "$session"
fi
